<footer>
    <a href="<?php if (!isset($isIndex)) { echo '../index.php'; } ?>">Acceuil</a>

    <?php if (!isset($isIndex)) { ?>
        <form action="" method="post" id="previous">
            <fieldset>
                <input type="hidden" name="userName" value="<?= $_POST["userName"] ?>">
                <?php if (!is_numeric($_POST["nodeNumber"])) { ?>
                    <input type="hidden" name="nodeNumber" value="<?= $winContainer[$_POST["nodeNumber"]]["previousNode"] ?>">
                <?php } else if ($_POST["nodeNumber"] >= 0) { ?>
                    <input type="hidden" name="nodeNumber" value="<?= $nodeContainer[$_POST["nodeNumber"]]["previousNode"] ?>">
                <?php } else { ?>
                    <input type="hidden" name="nodeNumber" value="<?= $failContainer[($_POST["nodeNumber"] * -1) - 1]["previousNode"] ?>">
                <?php } ?>
            </fieldset>
            <fieldset>
                <button type="submit" id="previousButton">Précédent</button>
            </fieldset>
        </form>
    <?php } ?>

    <a>Arbre</a>
</footer>